language: cpp
before_install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake libmgl-dev libmgl-qt*

script:
  - ln -s /usr/include/mgl libraries/mgl2
  - qmake -project
  - qmake NSGA-II.pro
  - make
